### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by newmanw** [xni06/JCoord#3]
Need a license file.

**Comment by nickw1** [comment]
99% sure the original JCoord license was GPL (not LGPL) but worth double checking.

**Comment by xni06** [comment]
@nickw1 The licence incorporated in the README.MD states GPL not LGPL - where do you see LGPL?

**Comment by nickw1** [comment]
@xni06 Sorry if my comment above was unclear... I meant I was 99% sure that the original JCoord license was GPL- as you have confirmed - I wanted to make it clear that the license was GPL and not LGPL, as LGPL is a commonly-used license for libraries. Sorry for the confusion!
