### ISSUE TITLE
Leading zeros in getOsRefWithPrecisionOf(SIX_DIGITS)

### ISSUE THREAD

**Issue by nickw1** [xni06/JCoord#7]
Noticed that OSRef.getOsRefWithPrecisionOf() with six digit precision adds leading zeros to the grid reference.

For instance 489600m, 128500m gets converted to SU08960285.

Is this intended behaviour? Would expect SU896285.

I am quite happy to fix this myself if the leading zeros are indeed erroneous.

**Comment by xni06** [comment]
TBH, I don't know what it should be as I'm no expert in this field - you'd have to ask the [author](http://www.jstott.me.uk/jcoord) :-/ 

In his absence, all I can say is that your assumption sounds correct having injected them into http://www.fieldenmaps.info/cconv/cconv_gb.html

Feel free to add a _breaking test_ then make the relevant changes.

In the meantime, we can see whether anyone else has any comments.

**Comment by nickw1** [comment]
OK. BTW it's not just an assumption, the OS document it explicitly; see six-figure refs at: https://getoutside.ordnancesurvey.co.uk/guides/beginners-guide-to-grid-references/

**Comment by xni06** [comment]
Would you like to create a PR?

**Comment by nickw1** [comment]
Fixed in PR #10; therefore now closed.
